# pyproject.toml
[project]
name = "comfyui-imageautosize" # Unique identifier for your node. Immutable after creation.
description = "A node for ComfyUI that provides a convenient way of resizing or cropping an image for diffusion tasks."
version = "0.0.1" # Custom Node version. Must be semantically versioned.
license = { file = "LICENSE.txt" }
dependencies  = [] # Filled in from requirements.txt

[project.urls]
Repository = "https://github.com/SparknightLLC/ComfyUI-ImageAutosize"

[tool.comfy]
PublisherId = "sparknight" # TODO (fill in Publisher ID from Comfy Registry Website).
DisplayName = "ComfyUI-ImageAutosize" # Display name for the Custom Node. Can be changed later.
Icon = "https://example.com/icon.png" # SVG, PNG, JPG or GIF (MAX. 800x400px)